In [4]:
!pip install numpy


In [3]:
import numpy as np

Using List Time is

In [5]:
from time import process_time

In [11]:
python_list = [i for i in range(100000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.012655436999999381


Using Numpy Array

In [12]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0003019369999996968


Numpy Array

In [15]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [16]:
# creating 1-D Array
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [17]:
a.shape

(4,)

In [18]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
b.shape

(2, 4)

In [20]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Place Holder in numpy Array

In [22]:
#create numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
z= np.full((5,5), 10)
print(z)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [33]:
# How to create Identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# Create a numpy array with random values
b= np.random.random((3,4))
print(b)

[[0.70767697 0.74775395 0.41705843 0.78172369]
 [0.81327536 0.43753206 0.0957607  0.40406521]
 [0.59417974 0.29115214 0.16852188 0.61804078]]


In [35]:
# random values array integer values with specific range
c= np.random.randint(10,100,(3,5))
print(c)


[[92 45 86 65 62]
 [97 98 63 64 14]
 [98 57 18 82 88]]


In [38]:
# array of evenly spaced values number of values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [41]:
e = np.arange(10,100,10)
print(e)

[10 20 30 40 50 60 70 80 90]


In [43]:
#convert list to numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array
mathematical operation
array manipulation
reshape array